#!/bin/bash

if (( $# != 1 )); then
    echo "Illegal number of parameters"
    echo "Usage: $0 <volume-number>"
    exit 1
fi

if [ "$1" -ge 120 ]; then
    echo "ERROR: Volume value $1 is too high"
    exit 1
fi

amixer sset Digital "$@"
