#!/bin/bash

if [ "$#" -ge 2 ]; then
    echo "Illegal number of parameters"
    echo "Usage: $0 [<volume-number>]"
    exit 1
elif [ "$#" -eq 1 ]; then
    if [ "$1" -ge 120 ]; then
	echo "Volume too high"
	exit 1
    fi
    amixer sset Digital "$1" >/dev/null
else
    amixer sget Digital | grep ': Playback .* \[' | awk '{print $4}' | head -1
fi
